<?php

declare(strict_types=1);

namespace ThePHPBench\Seed;

final class SqlEmitter
	{
	/**
	 * @param list<array<string, scalar|null>> $rows
	 * @return list<string>
	 */
	public function emit(ScenarioDefinition $scenario, string $backend, array $rows, int $insertBatchSize = 1) : array
		{
		$backend = \strtolower($backend);

		if (! \in_array($backend, ['sqlite', 'mysql', 'mariadb', 'pgsql', 'postgres', 'postgresql'], true))
			{
			throw new \InvalidArgumentException("Unsupported backend: {$backend}");
			}

		$normalized = match ($backend) {
			'postgres', 'postgresql' => 'pgsql',
			default => $backend,
		};

		$table = $scenario->getTableName();
		$statements = [
			$this->dropTable($table, $normalized),
			$this->createTable($scenario, $normalized),
		];

		foreach ($scenario->indexedColumns as $column)
			{
			$statements[] = \sprintf(
				'CREATE INDEX %s ON %s (%s);',
				$this->identifier("idx_{$table}_{$column}", $normalized),
				$this->identifier($table, $normalized),
				$this->identifier($column, $normalized),
			);
			}

		$insertBatchSize = \max(1, $insertBatchSize);

		foreach (\array_chunk($rows, $insertBatchSize) as $chunk)
			{
			$statements[] = 1 === \count($chunk)
				? $this->insert($table, $chunk[0], $normalized)
				: $this->insertBatch($table, $chunk, $normalized);
			}

		return $statements;
		}

	private function dropTable(string $table, string $backend) : string
		{
		return 'DROP TABLE IF EXISTS ' . $this->identifier($table, $backend) . ';';
		}

	private function createTable(ScenarioDefinition $scenario, string $backend) : string
		{
		$columns = [];

		foreach ($scenario->fields as $field)
			{
			$columns[] = '  ' . $this->identifier($field->name, $backend) . ' ' . $this->columnType($field, $backend);
			}

		return "CREATE TABLE " . $this->identifier($scenario->getTableName(), $backend) . " (\n" . \implode(",\n", $columns) . "\n);";
		}

	private function columnType(FieldDefinition $field, string $backend) : string
		{
		if ('id' === $field->type)
			{
			return match ($backend) {
				'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
				'mysql', 'mariadb' => 'INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY',
				'pgsql' => 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
			};
			}

		$type = match ($field->type) {
			'boolean' => 'BOOLEAN',
			'smallint' => 'SMALLINT',
			'integer' => 'INTEGER',
			'bigint' => 'BIGINT',
			'float' => 'FLOAT',
			'double' => 'pgsql' === $backend ? 'DOUBLE PRECISION' : 'DOUBLE',
			'decimal' => 'DECIMAL(' . $field->precision . ',' . $field->scale . ')',
			'char' => 'CHAR(' . $field->length . ')',
			'varchar' => 'VARCHAR(' . $field->length . ')',
			'text' => 'TEXT',
			'date' => 'DATE',
			'datetime' => 'pgsql' === $backend ? 'TIMESTAMP' : 'DATETIME',
			default => throw new \InvalidArgumentException("Unhandled field type: {$field->type}"),
		};

		return $type . ($field->nullable ? '' : ' NOT NULL');
		}

	/**
	 * @param array<string, scalar|null> $row
	 */
	private function insert(string $table, array $row, string $backend) : string
		{
		$columns = [];
		$values = [];

		foreach ($row as $column => $value)
			{
			$columns[] = $this->identifier($column, $backend);
			$values[] = $this->literal($value);
			}

		return \sprintf(
			'INSERT INTO %s (%s) VALUES (%s);',
			$this->identifier($table, $backend),
			\implode(', ', $columns),
			\implode(', ', $values),
		);
		}

	/**
	 * @param list<array<string, scalar|null>> $rows
	 */
	private function insertBatch(string $table, array $rows, string $backend) : string
		{
		$firstRow = $rows[0] ?? [];
		$columns = \array_map(fn(string $column) : string => $this->identifier($column, $backend), \array_keys($firstRow));
		$valueGroups = [];

		foreach ($rows as $row)
			{
			$valueGroups[] = '(' . \implode(', ', \array_map(fn(string|int|float|bool|null $value) : string => $this->literal($value), \array_values($row))) . ')';
			}

		return \sprintf(
			'INSERT INTO %s (%s) VALUES %s;',
			$this->identifier($table, $backend),
			\implode(', ', $columns),
			\implode(",\n", $valueGroups),
		);
		}

	private function identifier(string $identifier, string $backend) : string
		{
		return match ($backend) {
			'mysql', 'mariadb' => '`' . $identifier . '`',
			default => '"' . $identifier . '"',
		};
		}

	private function literal(string|int|float|bool|null $value) : string
		{
		if (null === $value)
			{
			return 'NULL';
			}

		if (\is_bool($value))
			{
			return $value ? 'TRUE' : 'FALSE';
			}

		if (\is_int($value) || \is_float($value))
			{
			return (string)$value;
			}

		return "'" . \str_replace("'", "''", $value) . "'";
		}
	}
